export type { DimensionalFormula } from './units/dimensionalFormula';
export type { DerivedUnitInfo } from './units/derivedUnitInfo';
export type { CalcValue, CategoryDimensionInfo, SIRepresentation, AlternativeRepresentation, NormalizableDerivedUnit, DerivedUnitPowerMatch } from './calculator/types';

export { dimensionsEqual } from './dimensions/dimensionsEqual';
export { isDimensionless } from './dimensions/isDimensionless';
export { isDimensionEmpty } from './dimensions/isDimensionEmpty';
export { multiplyDimensions } from './dimensions/multiplyDimensions';
export { divideDimensions } from './dimensions/divideDimensions';
export { subtractDimensions } from './dimensions/subtractDimensions';
export { toSuperscript } from './calculator/toSuperscript';
export { formatDimensions } from './calculator/formatDimensions';
export { isValidSymbolRepresentation } from './calculator/isValidSymbolRepresentation';
export { countUnits } from './calculator/countUnits';
export { sumAbsExponents } from './calculator/sumAbsExponents';
export { canAddSubtract } from './calculator/canAddSubtract';
export { canFactorOut } from './calculator/canFactorOut';
export { hasOnlyOriginalDimensions } from './calculator/hasOnlyOriginalDimensions';
export { isValidSIComposition } from './calculator/isValidSIComposition';
export { formatSIComposition } from './calculator/formatSIComposition';
export { canApplyDerivedUnit } from './calculator/canApplyDerivedUnit';
export { subtractDerivedUnit } from './calculator/subtractDerivedUnit';

export { CATEGORY_DIMENSIONS, EXCLUDED_CROSS_DOMAIN_CATEGORIES } from './calculator/categoryDimensions';
export { SI_DERIVED_UNITS, SPECIALTY_DERIVED_UNITS, SI_UNITS_BY_COMPLEXITY, GENERAL_SI_DERIVED, NORMALIZABLE_DERIVED_UNITS } from './calculator/siDerivedUnits';

export { findCrossDomainMatches } from './calculator/findCrossDomainMatches';
export { findDerivedUnitPower } from './calculator/findDerivedUnitPower';
export { normalizeDimensions } from './calculator/normalizeDimensions';
export { generateSIRepresentations, PREFERRED_REPRESENTATIONS } from './calculator/generateSIRepresentations';
export { generateAlternativeRepresentations } from './calculator/generateAlternativeRepresentations';
export { getDerivedUnit } from './calculator/getDerivedUnit';
export { isRadians } from './dimensions/isRadians';
export { fixPrecision } from './calculator/fixPrecision';
export { buildDirectUnitSymbol } from './calculator/buildDirectUnitSymbol';
export { buildDirectDimensions } from './calculator/buildDirectDimensions';
export type { RpnUnaryOp } from './calculator/applyRpnUnary';
export { applyRpnUnary } from './calculator/applyRpnUnary';
export type { RpnBinaryOp } from './calculator/applyRpnBinary';
export { applyRpnBinary } from './calculator/applyRpnBinary';
